version: '3.5'

services:
  postgres:
    container_name: capesdb
    image: postgres:10
    restart: always
    networks:
      - frontend
    ports:
      - "5433:5432"
    volumes:
     - ./data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: capesdb
      POSTGRES_USER: capesdb_user
      POSTGRES_PASSWORD: c4pes

  pgadmin:
    container_name: capes_pgadmin
    image: dpage/pgadmin4
    networks:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user
      PGADMIN_DEFAULT_PASSWORD: pass

  jupyter:
    container_name: capes_jnotebook
    #image: jupyter/datascience-notebook:137a295ff71b
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    networks:
     - frontend
    ports:
     - "8888:8888"
    volumes:
       - ../analysis:/home/jovyan
    environment:
      JUPYTER_LAB_ENABLE: "yes"

networks:
  frontend:
    name: capesdb_net
