SELECT DISTINCT 
	ID_PESSOA
	,NM_DOCENTE
	,AN_BASE
	,CD_CAT_BOLSA_PRODUTIVIDADE
FROM FATO_DOCENTE 
WHERE 
	SG_ENTIDADE_ENSINO = 'UFPA' 
	AND NM_PROGRAMA_IES = 'ENGENHARIA ELÉTRICA'
	AND AN_BASE = 2016
ORDER BY NM_DOCENTE ASC 
